### ISSUE TITLE
Protected pages

### ISSUE THREAD

**Issue by JustDenP** [vendure-ecommerce/storefront-sveltekit-starter#38]
@jycouet Hello!,

I'm trying to configure the protected pages system, but so far without success. I have a slightly different scenario, because I’m not doing a storefront, but a seller dashboard, but the logic is the same.

I wanted to protect the application using hooks.server.ts, but inside it I cannot get the Autherntication Bearer token, which is assigned in the client.ts file to every request.

The only way I have succeeded is through +page.ts, but I'm afraid this is a very unreliable solution.

I also tried to set up a simpler system using cookies, but I can't figure out where to set withCredentials: true as on other clients.

Please, can you explain what I'm doing wrong and how I can insert the Autherntication Bearer token into the hooks.server file

I made a repository for greater clarity. 🙏 Thank you
https://github.com/JustDenP/svelte-houdini

**Comment by jycouet** [comment]
👋 hi, 

Not that easy to help, I cloned the repo, but without the server, I can't do much.

Yes, I would say that cookie is the way to go.
You can `withCredentials: true` in the`fetchParams` function and/or in your `await fetch` that you created in the `client.ts`

We can chat on discord if it's easier?

**Comment by JustDenP** [comment]
Thank you! I will definitely try cookies again

One more small question, I'm trying to figure out how to make the architecture of my app in advance, and the page.gql files always appear in the documentation as the main ones for loading queries

But do I understand correctly that I cannot insert 2 or more queries into these files? This is not stated in the documentation, but in reality it produces an error.

I just can’t imagine that there should be only one request on the pages, so in my case I need to stick to manual loads, like this?

```ts
export const load: LayoutLoad = async event => {
  return {
    ...(await load_GetTopSellers({ event })),
    ...(await load_LayoutQuery({ event })),
    ...(await load_GetCollections({ event })),
  }
}
```

**Comment by jycouet** [comment]
Hummm, I don't know how to answer easily ^^. As "everything" is possible.
After it depends on the context 👍

Yes, One file = One query _(It's not an error, it's in purpose like this)_
I guess you wanted to do:
```gql
query GetTopSellers {
  topSellers {
    name
  }
}

query GetCollections{
  collections {
    name
  }
}
```
Q1: But why not doing?
```gql
query GetTopSellersAndCollections {
  topSellers {
    name
  }
  collections {
    name
  }
}
```

---

If not, with the `load_xxx` you can use the utility `loadAll` to have everything in parallel.
You can check https://houdinigraphql.com/api/query#manual-loading with the part "Loading multiple stores simultaneously" to have some example.

---

In your situation, I would do a `+layout.gql` with fragments for `Sellers`, for `Collections`, ...

---

Hope it helps 

//Happy coding

**Comment by JustDenP** [comment]
Thank you for detailed answer!
